irc_client/gui.py
=> Tab completion

irc_client/gui.py
=> Notifications when someone mentions your nick

irc_client/backend.py
=> ssl module best practices

irc_client/__main__.py, irc_client/backend.py, irc_client/config.py, irc_client/gui.py, pyproject.toml
=> big code cleanup, introduce ConnectivityMessage

irc_client/__main__.py, irc_client/backend.py, irc_client/config.py
Most servers use ssl, and that will continue to be the default, but non-SSL connections are useful when testing with irc server on localhost.
=> ssl checkbox

irc_client/__main__.py, irc_client/backend.py, irc_client/colors.py, irc_client/config.py, irc_client/gui.py, tests/conftest.py, tests/test_commands.py, tests/test_config.py, tests/test_messaging.py
=> Optionally notifications for all messages

irc_client/backend.py, irc_client/colors.py, irc_client/config.py, irc_client/gui.py, tests/test_messaging.py
=> Nick coloring fixes

irc_client/backend.py, irc_client/commands.py, irc_client/gui.py, irc_client/views.py, tests/test_commands.py, tests/test_connection_errors.py
=> topic stuff

irc_client/__main__.py, irc_client/gui.py, irc_client/views.py, tests/conftest.py, tests/test_commands.py, tests/test_connection_errors.py, tests/test_messaging.py
=> Support multiple servers, if specified in config file

irc_client/__main__.py, irc_client/gui.py, tests/test_commands.py
=> fix bugs when parting all channels or quitting all servers

irc_client/__main__.py, irc_client/backend.py, irc_client/config.py, irc_client/views.py, tests/conftest.py, tests/test_config.py
=> sasl (this time with less merge conflicts)

irc_client/backend.py, irc_client/config.py, irc_client/gui.py, irc_client/views.py, tests/test_config.py, tests/test_connection_errors.py, tests/test_logging.py
=> Server config on right-click

irc_client/backend.py, tests/test_connection_errors.py
=> Backend: fix bug with wrong order of messages

irc_client/commands.py, irc_client/config.py, irc_client/gui.py, irc_client/views.py, tests/test_commands.py, tests/test_messaging.py
=> go through TODO comments, fix small things

mantaray/__main__.py, mantaray/colors.py, mantaray/config.py, mantaray/gui.py, mantaray/views.py, tests/conftest.py, tests/test_config.py, tests/test_messaging.py
=> Font size with Ctrl+Plus Ctrl+Minus (Cmd on Mac)

mantaray/__main__.py, mantaray/colors.py, mantaray/gui.py, requirements-dev.txt, requirements.txt
=> Dark theme

mantaray/gui.py, tests/test_messaging.py
=> allow entry autocompletions anywhere

mantaray/commands.py, mantaray/gui.py, tests/test_commands.py, tests/test_messaging.py
=> Sending multiple lines at once

mantaray/__main__.py, mantaray/gui.py, tests/test_commands.py
=> keybinding fixes

.gitignore, mantaray/__main__.py
=> delete --no-config argument, replace with --config-dir

.github/workflows/check.yml
=> github actions timeout

mantaray/__main__.py, mantaray/commands.py, mantaray/gui.py, mantaray/views.py, tests/conftest.py, tests/test_commands.py, tests/test_connection_errors.py, tests/test_messaging.py, tests/test_notifications.py
=> Rewrite notifications code

mantaray/views.py
=> fix pm conversations image

alice/config.json, bob/config.json, tests/conftest.py, tests/test_config.py
=> Get rid of duplicate example configs

mantaray/commands.py, tests/test_commands.py
=> Commands cleanup

mantaray/backend.py, mantaray/commands.py, mantaray/gui.py, mantaray/views.py, tests/conftest.py, tests/test_commands.py, tests/test_connection_errors.py, tests/test_messaging.py, tests/test_notifications.py
=> fix ThePhilgrim's confusion

mantaray/gui.py, tests/test_messaging.py
https://user-images.githubusercontent.com/76887896/147389843-2222fba7-0bdf-4e13-a19d-54e0bdc3baaa.mov
=> Clear entry if pressing down arrow with last msg in entry

mantaray/__main__.py, mantaray/views.py, tests/conftest.py, tests/test_commands.py, tests/test_messaging.py, tests/test_notifications.py
=> align text correctly and make window bigger by default

.github/workflows/check.yml, .gitignore, .gitmodules, README.md, tests/conftest.py, tests/test_commands.py, tests/test_connection_errors.py, tests/test_messaging.py
This way, mantaray's tests can be used in CI of irc servers.
=> make hircd a submodule and allow using custom irc server

mantaray/gui.py
=> decrease indentation in view selector

mantaray/backend.py, mantaray/commands.py, tests/test_messaging.py
=> do not split messages on \r

mantaray/__main__.py
=> validate --config-dir

mantaray/commands.py
=> add /cs and /chanserv

mantaray/__main__.py, mantaray/backend.py, mantaray/gui.py, mantaray/views.py
=> add --verbose option

.github/workflows/check.yml
If this works, it simplifies the config slightly
=> github actions: use xvfb-action on all platforms

.gitmodules, pyproject.toml, tests/conftest.py
Was confusing to have both `mantaray` and `mantatail` in the same folder
=> Move IRC server git submodules into tests/

.github/workflows/check.yml, mantaray/backend.py, mantaray/gui.py, mantaray/views.py, tests/conftest.py, tests/test_commands.py, tests/test_connection_errors.py, tests/test_logging.py, tests/test_messaging.py
=> Yet another attempt to get tests working on Macos

mantaray/gui.py, mantaray/views.py, tests/test_messaging.py
Attempts to fix a couple rarely happening bugs
=> Tests fixes

mantaray/backend.py
Should make mantaray less annoying to use and develop
=> reconnect sooner

mantaray/backend.py, mantaray/commands.py, mantaray/views.py, tests/conftest.py, tests/test_commands.py
=> MODE support

mantaray/views.py, tests/test_commands.py
=> Show kick reason to the person being kicked, add tests

mantaray/backend.py, mantaray/received.py, mantaray/views.py, tests/test_config.py, tests/test_notifications.py
I will clean up the 260 lines long function in a separate PR.
=> Move event handling code from views to a separate file

mantaray/commands.py, tests/test_commands.py
=> Make commands case insensitive

mantaray/backend.py, mantaray/received.py
Should make the code a lot more readable, and easier to work on
=> Big diff: refactor handling received commands

tests/test_logging.py, tests/test_messaging.py
Makes #194 and #197 less annoying
=> skip autocomplete and logging tests on github actions

mantaray/received.py, tests/test_commands.py
=> display QUIT messages only on channels where the user was

tests/conftest.py, tests/test_logging.py
=> Try to make logging tests more stable

mantaray/received.py, mantaray/views.py, tests/test_messaging.py
=> Prevent two PMViews with same nick

mantaray/backend.py, mantaray/commands.py, mantaray/received.py, tests/test_notifications.py
=> Rethink _JoinInProgress code

mantaray/commands.py, tests/test_commands.py
=> fix kick and op/deop error messages add_message calls

mantaray/textwidget_tags.py, mantaray/views.py
=> Make nick names clickable

mantaray/backend.py
=> Make the select loop work with ssl

mantaray/backend.py, mantaray/received.py, mantaray/views.py, tests/conftest.py, tests/test_commands.py
=> Fix error when talking after kick and improve error reporting in tests

mantaray/received.py, mantaray/views.py, tests/test_commands.py
=> preserve away status when nick changes

mantaray/backend.py, mantaray/commands.py, mantaray/gui.py, mantaray/history.py, mantaray/received.py, mantaray/textwidget_tags.py, mantaray/views.py, tests/test_commands.py, tests/test_config.py, tests/test_history.py, tests/test_messaging.py, tests/test_notifications.py
=> Rewrite history code

mantaray/textwidget_tags.py, tests/test_messaging.py
=> do not tag nicks in middle of url

mantaray/commands.py, tests/test_commands.py, tests/test_config.py, tests/test_logging.py
It has problems:
- It quits only the current server. If you have multiple servers, you lose all information about the server you quit (username, password, joined channels, host, port, ...)
- It doesn't save settings
Fixes #149
=> Delete /quit command

.gitignore, README.md, tests/test_history.py
=> README: explain and recommend --config-dir, explain netcat/telnet

tests/conftest.py, tests/test_messaging.py
A continuation of #221.
Example failures:
https://github.com/Akuli/mantaray/runs/5259678021?check_suite_focus=true
https://github.com/Akuli/mantaray/runs/5259562623?check_suite_focus=true
=> Try to fix test_private_messages_nick_changing_bug again

mantaray/received.py, tests/test_notifications.py
=> handle /me and notifications better

mantaray/received.py
=> MODE fix, part 2

mantaray/received.py, mantaray/textwidget_tags.py
=> Use channel tag (color) more. Add topic tag

.github/workflows/check.yml, requirements-dev.txt
CI has started failing at some point. Making it work is basically necessary for other people to contribute.
=> Try to get CI to work again

tests/conftest.py
Seems to help with #241, not yet sure if fixes it or not.
=> Improve port in use error handling in tests

mantaray/config.py, mantaray/gui.py, tests/test_config.py
Checks the most important box in #304
=> Remember view selector and userlist widths

mantaray/textwidget_tags.py, tests/test_messaging.py
=> Do not allow non-break space in URLs

mantaray/commands.py
To me it focuses already on linux, but this should help on macos. Fixes #107
=> Focus entry after pasting multiple lines

mantaray/views.py, requirements-dev.txt
ThePhilgrim contributed playsound stubs to typeshed just for this, but apparently we never applied the stubs here.
=> Use types-playsound

mantaray/__main__.py, mantaray/gui.py, mantaray/received.py, mantaray/right_click_menus.py, mantaray/textwidget_tags.py, mantaray/views.py, tests/test_config.py
Fixes #276
Checks a box in #304
=> Add right-click menu with option to send PM

mantaray/commands.py, mantaray/received.py, mantaray/views.py, tests/test_commands.py
=> Show away reason in userlist

mantaray/views.py
Fixes #319
https://user-images.githubusercontent.com/18505570/230891854-594d593a-f25e-4a80-a907-54e41d968228.mp4
https://user-images.githubusercontent.com/18505570/230891859-b82b9a6c-022c-460f-8e2c-1ea33778e190.mp4
=> Add a tooltip that shows long away reasons

.github/workflows/check.yml, mantaray/__main__.py
=> Fix import error handling

mantaray/views.py
=> Userlist hover: do not assume nick is still visible

mantaray/gui.py
=> Fix nick dialog messed up layout
