Akuli/mantaray

- irc_client/backend.py
- irc_client/gui.py
- Replace internal queue with a simpler send queue.
- Make sure that it is clear from method names which methods send and which receive.
- Use dataclasses instead of Enum+Any for events.
> backend cleanup

- mantaray/gui.py
> make right-click menu appear slightly next to mouse

- mantaray/config.py
- mantaray/gui.py
- mantaray/views.py
- tests/conftest.py
- tests/test_commands.py
- tests/test_config.py
> option to hide join/part/quit messages

- alice/config.json
- bob/config.json
- mantaray/gui.py
- mantaray/logs.py
- mantaray/views.py
- tests/conftest.py
- tests/test_config.py
- tests/test_logging.py
Handles corner cases better and fixes #151.
Todo:
> Logging improvements

- .github/workflows/check.yml
A short name leaves more room for other stuff in GitHub's UI.
> github actions: name the workflow

- .github/workflows/check.yml
Space is tight in the UI, and the test names easily get truncated so much that you can't see what OS or IRC server the test is using.
Related: #180
> Make tests show up better on github actions

- mantaray/backend.py
- mantaray/views.py
- pyproject.toml
- tests/conftest.py
- tests/test_commands.py
- tests/test_connection_errors.py
> Show server's error messages to the user instead of hiding in server tab

- mantaray/backend.py
- tests/conftest.py
While debugging, I had the idea of printing a stack trace of a different thread. I also realized I can join with a timeout, so that if nothing freezes, no debugging info is printed.
Rewrites everything added in #223
> improve wait_for_threads_to_stop

- mantaray/backend.py
- mantaray/gui.py
- mantaray/received.py
- mantaray/views.py
- tests/conftest.py
- tests/test_config.py
- tests/test_connection_errors.py
- tests/test_logging.py
This time there's no threads, except when connecting or disconnecting. Fixes #245, and hopefully prevents random and inconsistent freezes and errors in tests.
> Rewrite the backend once again

- mantaray/received.py
- tests/test_commands.py
Was confusing when the "you were redirected from #foo to #bar" error showed up in a completely unrelated channel, only because that happened to be the current channel during the autojoining.
> Put error messages to all views

- tests/conftest.py
Tests have been very stable and reliable since #247. Apparently threads were too hard for me to get right. 
Also, yes, it kept failing with the longer timeout.
> delete unnecessary longer timeout from conftest

- tests/test_commands.py
Closes #53. It was already fixed in #249, but now there's a test for the fix too.
> add test for not an operator error while changing topic

- mantaray/received.py
- tests/test_commands.py
Fixes #64 
I no longer use nickserv, because mantaray makes using SASL authentication so easy. But if someone is stuck with nickserv, we might as well not punish them by saving their password to the log file every time they log in.
> hide nickserv passwords

- mantaray/received.py
Fixes #238. Filtering the output of `--verbose` to only the lines that contain `WHO`, I get this on libera when I connect:
```
Send: b'WHO #c\r\n'
Recv: b':strontium.libera.chat 315 Akuli #c :End of /WHO list.\r\n'
Send: b'WHO #devuan-offtopic\r\n'
Recv: b':strontium.libera.chat 315 Akuli #devuan-offtopic :End of /WHO list.\r\n'
Send: b'WHO #devuan\r\n'
Recv: b':strontium.libera.chat 315 Akuli #devuan :End of /WHO list.\r\n'
Send: b'WHO #ircv3\r\n'
Recv: b':strontium.libera.chat 315 Akuli #ircv3 :End of /WHO list.\r\n'
Send: b'WHO #8banana\r\n'
Recv: b':strontium.libera.chat 315 Akuli #8banana :End of /WHO list.\r\n'
Send: b'WHO ##akuli-testing\r\n'
Recv: b':strontium.libera.chat 315 Akuli ##akuli-testing :End of /WHO list.\r\n'
Send: b'WHO ##guitar\r\n'
Recv: b':strontium.libera.chat 315 …
```
> Send the next WHO only after the previous WHO reply ends

- tests/conftest.py
Reading the pipe after each test finished worked well, until the operating system's buffer became full, and hircd stopped working while it was stuck printing. I believe this is what causes CI in #244 to error.
> tests: pipe irc server output to file

- mantaray/backend.py
- mantaray/received.py
- tests/conftest.py
- tests/test_config.py
This is a slightly hacky way to keep track of the usermask (which is actually called nickmask according to the Horse docs). It relies on sending a `WHOIS own_nick` to the server which then always replies with all components of the nickmask in `311 RPL_WHOISUSER`.
Ex:
```
Sent – WHOIS fubbe
Received – :copper.libera.chat 311 Fubbe Fubbe ~IAmTheFub 151.40.115.120 * :lol <---------
Received – :copper.libera.chat 312 Fubbe Fubbe copper.libera.chat :Sofia, BG
Received – :copper.libera.chat 338 Fubbe Fubbe 151.40.115.120 :actually using host
Received – :copper.libera.chat 317 Fubbe Fubbe 6 1644854035 :seconds idle, signon time
Received – :copper.libera.chat 318 Fubbe fubbe :End of /WHOIS list.
```
This should help to make it easier solving #172 (in a separate PR). This code would have to check …
> Keep track of own Usermask (nickmask)

- mantaray/backend.py
- mantaray/commands.py
- mantaray/gui.py
- mantaray/received.py
- tests/conftest.py
- tests/test_config.py
New logic is super simple: Keep track of the current nick in only one place, the settings. When you attempt to change the nick, nothing happens immediately. When the server tells you that your nick is now xyz, the settings updates and next time Mantaray sends `NICK xyz` when it starts.
> Simplify how nick name remembering works

- mantaray/received.py
Not really important because libera doesn't seem to do this, but might as well do it correctly instead of behaving weirdly (possibly getting stuck because `pending_cap_count` never drops to zero).
Completely untested. I don't know of any servers that would use this functionality so I could test this.
> Handle multiple CAPs at once

- mantaray/commands.py
This makes it possible to use commands that mantaray doesn't officially support yet. For example, `/raw NICK foo` is equivalent to `/nick foo`.
> Add a /raw command

- alice/config.json
This will hopefully prevent forgetting the light theme when I change something. I like to use
```
python3 -m mantaray --alice & python3 -m mantaray --bob &
```
when developing, with an IRC server (`python3 server.py` in MantaTail) running in a separate terminal.
> Use light theme in "python3 -m mantaray --alice"

- mantaray/config.py
For each setting there is:
- Type annotation
- A default value
- Reading the setting from the JSON dict
This combines everything into one-line `.get()` calls and gets rid of some copy/pasta.
> Refactor ServerSettings
